services:
  postgres:
    image: postgres:17
    container_name: my-garage-postgres
    environment:
      POSTGRES_DB: mygarage
      POSTGRES_USER: mygarage
      POSTGRES_PASSWORD: mygarage
    ports:
      - "15432:5432"
    volumes:
      - my-garage-postgres-data:/var/lib/postgresql/data

volumes:
  my-garage-postgres-data: