import { test, expect } from "@playwright/test";
import { installApiFixture, logIn } from "./api-fixture";

test("통합 알림은 양쪽 역할을 구분하고 확인 후 모드 전환에도 읽음 표시를 유지한다", async ({ page }) => {
  await installApiFixture(page);
  const now = Date.now();
  const incoming = { id: 401, vehicleId: 41, vehicleModel: "기아 EV9", ownerId: 1, renterId: 2, ownerName: "민수", renterName: "지민", pickupLocation: "서울 성수", startsAt: new Date(now + 3600000).toISOString(), endsAt: new Date(now + 10800000).toISOString(), status: "REQUESTED", termsVersion: "simulation-v1", terms: "계약 조건", ownerConsentedAt: null, renterConsentedAt: null, accessGrant: null, hourlyRate: 12000, estimatedTotal: 24000, billedHours: 2, lockState: "LOCKED", unlockRequests: [] };
  const borrowed = { ...incoming, id: 402, vehicleId: 42, vehicleModel: "현대 IONIQ 5", ownerId: 3, renterId: 1, status: "CONFIRMED", startsAt: new Date(now - 3600000).toISOString(), endsAt: new Date(now + 3600000).toISOString(), ownerConsentedAt: new Date(now - 4000000).toISOString(), renterConsentedAt: new Date(now - 4000000).toISOString() };
  let status = "REQUESTED";
  let noRentals = false;
  await page.route("**/api/rentals", route => route.fulfill({ json: noRentals ? [] : [{ ...incoming, status }, borrowed, { ...incoming, id: 999, ownerId: 9, renterId: 10 }] }));
  await page.route("**/api/vehicles/available**", route => route.fulfill({ json: [] }));
  await logIn(page); await page.goto("/owner");
  const bell = page.getByRole("button", { name: "알림 2개", exact: true });
  await expect(bell).toHaveClass(/has-unread/);
  await expect(bell.locator("svg")).toBeVisible();
  const card = page.locator('article[data-rental-id="401"]');
  await expect(card).toHaveClass(/owner-request-card/);
  await expect(card.locator(".request-period time strong").first()).toHaveCSS("font-size", "26px");
  await expect(card.getByRole("button", { name: "대여 승인", exact: true })).toBeVisible();
  await page.screenshot({ path: "/private/tmp/my-garage-unified-owner-request.png", fullPage: true });
  await bell.click();
  const dialog = page.getByRole("dialog", { name: "통합 알림" });
  await expect(dialog.getByText("차량 렌탈 신청이 왔어요", { exact: true })).toBeVisible();
  await expect(dialog.getByText("차량 렌탈 예약이 확정되었어요", { exact: true })).toBeVisible();
  await expect(dialog.locator('a[data-mode="owner"]')).toHaveCount(1);
  await expect(dialog.locator('a[data-mode="renter"]')).toHaveCount(1);
  expect(await dialog.locator(".notification-mode--owner").evaluate(n => getComputedStyle(n).color)).not.toBe(await dialog.locator(".notification-mode--renter").evaluate(n => getComputedStyle(n).color));
  await expect(dialog.locator('a[data-mode="owner"]')).toHaveAttribute("href", "/contracts/401");
  await page.screenshot({ path: "/private/tmp/my-garage-unified-notifications.png", fullPage: true });
  await dialog.getByRole("button", { name: "닫기", exact: true }).click();
  await page.getByRole("navigation", { name: "이용 모드" }).getByRole("link", { name: "차량 빌리기", exact: true }).click();
  await expect(page).toHaveURL(/\/renter$/);
  await expect(page.getByRole("button", { name: "알림 0개", exact: true })).not.toHaveClass(/has-unread/);
  await expect(page.getByRole("navigation", { name: "대여자 메뉴" })).toHaveCount(0);
  status = "CONTRACT_PENDING";
  await page.reload();
  await expect(page.getByRole("button", { name: "알림 1개", exact: true })).toHaveClass(/has-unread/);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "알림 1개", exact: true }).click();
  await expect(dialog.getByText("예약 승인이 완료됐어요. 계약에 동의해주세요", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "닫기", exact: true }).click();
  noRentals = true; await page.reload();
  await expect(page.getByRole("region", { name: "내 대여 요청 및 계약" })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "현재 이용 중인 차량" })).toHaveCount(0);
});
