"use client";
import { useState } from "react";
import { LargeSelect } from "@/components/ui/large-select";
import { RentalPeriodFields } from "./rental-period-fields";
export interface RenterFiltersState { search: string; manufacturer: string; model: string; electric: boolean; availableOnly: boolean; minPrice: string; maxPrice: string }
export const emptyRenterFilters: RenterFiltersState = { search: "", manufacturer: "", model: "", electric: false, availableOnly: false, minPrice: "", maxPrice: "" };
export function RenterFilters({ value, onChange, manufacturers, models, hasPrices, start, end, onStart, onEnd, validPeriod }: { value: RenterFiltersState; onChange: (value: RenterFiltersState) => void; manufacturers: string[]; models: string[]; hasPrices: boolean; start: string; end: string; onStart: (value: string) => void; onEnd: (value: string) => void; validPeriod: boolean }) {
  const [expanded, setExpanded] = useState(false);
  function change<K extends keyof RenterFiltersState>(key: K, next: RenterFiltersState[K]) { onChange({ ...value, [key]: next }); }
  return <aside className="renter-filters inventory-filters" aria-label="차량 검색 필터"><div className="renter-filter-heading"><h2>어떤 차량을 찾으세요?</h2><button type="button" onClick={() => onChange(emptyRenterFilters)}>초기화</button></div>
    <button type="button" className="renter-mobile-filter-toggle" aria-expanded={expanded} aria-controls="renter-filter-content" onClick={() => setExpanded(previous => !previous)}>{expanded ? "검색·필터 접기" : "검색·필터 열기"}</button><div id="renter-filter-content" className={`renter-filter-content ${expanded ? "is-open" : ""}`}>
    <label className="form-field">차량·픽업 주소 검색<input type="search" value={value.search} onChange={event => change("search", event.target.value)} placeholder="차량 이름이나 지역 검색" /></label>
    <div className="renter-filter-group"><LargeSelect label="제조사" value={value.manufacturer} placeholder="전체 제조사" options={[{ value: "", label: "전체 제조사" }, ...manufacturers.map(name => ({ value: name, label: name }))]} onChange={manufacturer => onChange({ ...value, manufacturer, model: "" })} /><LargeSelect label="차종" value={value.model} placeholder="전체 차종" options={[{ value: "", label: "전체 차종" }, ...models.map(name => ({ value: name, label: name }))]} onChange={model => change("model", model)} /></div>
    <fieldset className="renter-price-filter"><legend>시간당 가격 범위</legend><div><label className="form-field">최소 금액<input type="number" min="0" step="1000" inputMode="numeric" disabled={!hasPrices} placeholder="최소 가격" value={value.minPrice} onChange={event => change("minPrice", event.target.value)} /></label><span aria-hidden="true">–</span><label className="form-field">최대 금액<input type="number" min="0" step="1000" inputMode="numeric" disabled={!hasPrices} placeholder="최대 가격" value={value.maxPrice} onChange={event => change("maxPrice", event.target.value)} /></label></div><p>{hasPrices ? "원/시간 · 가격 조건 적용 시 요금 미등록 차량 제외" : "등록된 요금이 없어 가격 필터를 사용할 수 없습니다."}</p>{value.minPrice && value.maxPrice && Number(value.minPrice) > Number(value.maxPrice) && <p role="status">최대 금액을 최소 금액 이상으로 입력해주세요.</p>}</fieldset>
    <div className="renter-filter-group"><label className="sharing-toggle"><input type="checkbox" checked={value.electric} onChange={event => change("electric", event.target.checked)} />전기차만 보기</label><label className="sharing-toggle"><input type="checkbox" checked={value.availableOnly} onChange={event => change("availableOnly", event.target.checked)} />대여 가능한 차량만</label></div>
    <div className="renter-filter-group"><h3>언제 이용하시나요?</h3><RentalPeriodFields start={start} end={end} onStart={onStart} onEnd={onEnd} browsing />{!validPeriod && <p role="status" className="field-hint">시작보다 뒤인 종료 시각을 선택해주세요.</p>}<p className="field-hint">선택한 기간의 예약 가능 여부를 확인합니다.</p></div>
  </div></aside>;
}
